version: '3.8'
services:
  db:
    image: mysql:8.0.43
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: calendar
      MYSQL_USER: calendar_user
      MYSQL_PASSWORD: calendar_password
      MYSQL_ROOT_HOST: '%'
    ports:
      - "3306:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-proot_password" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - backend
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
