spring:
  application:
    name: calendar-service
  datasource:
    url: jdbc:mysql://db:3306/calendar?serverTimezone=UTC&useSSL=false
    username: calendar_user
    password: calendar_password
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      initialization-fail-timeout: 100000
      connection-timeout: 100000
  flyway:
    enabled: false
    locations: classpath:db/migration
    baseline-on-migrate: true

server:
  port: 8080